<a href="https://colab.research.google.com/github/LCaravaggio/Happiness_Polarization/blob/main/Serie_de_tiempo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Instalación de paquetes

In [1]:
!pip install linearmodels

Collecting linearmodels
  Downloading linearmodels-7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (2.0.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (2.2.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (1.16.3)
Requirement already satisfied: statsmodels>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from linearmodels) (0.14.6)
Collecting mypy_extensions>=0.4 (from linearmodels)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pyhdfe>=0.1 (from linearmodels)
  Downloading pyhdfe-0.2.0-py3-none-any.whl.metadata (4.0 kB)
Collecting formulaic>=1.2.1 (from linearmodels)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.2.1->linearmodels)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (2.22.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.2.1->linearmodels) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->linearmodels) (2026.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->linearmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.0->linearmodels) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->linearmodels) (1.17.0)
Downloading linearmodels-7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 14.3 MB/s eta 0:00:00
Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.9/118.9 kB 3.7 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pyhdfe-0.2.0-py3-none-any.whl (19 kB)
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Installing collected packages: mypy_extensions, interface-meta, pyhdfe, formulaic, linearmodels
Successfully installed formulaic-1.2.2 interface-meta-2.0.1 linearmodels-7.0 mypy_extensions-1.1.0 pyhdfe-0.2.0

In [2]:
!pip install pydynpd

Collecting pydynpd
  Downloading pydynpd-0.2.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pydynpd) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pydynpd) (1.16.3)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from pydynpd) (3.17.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pydynpd) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pydynpd) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pydynpd) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pydynpd) (2026.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable->pydynpd) (0.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pydynpd) (1.17.0)
Downloading pydynpd-0.2.2-py3-none-any.whl (26 kB)
Installing collected packages: pydynpd
Successfully installed pydynpd-0.2.2

# Carga de Datos

In [3]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import re

BASE = "https://www.latinobarometro.org"
INDEX = f"{BASE}/agregados"

headers = {
    "User-Agent": "Mozilla/5.0"
}

# =========================
# 1. obtener páginas de cada ola
# =========================

html = requests.get(INDEX, headers=headers).text
soup = BeautifulSoup(html, "html.parser")

wave_pages = []

for a in soup.find_all("a", href=True):

    href = a["href"]

    # links tipo /latinobarometro-2023
    if re.search(r"latinobarometro-\d{4}$", href):

        full = urljoin(BASE, href)
        wave_pages.append(full)

wave_pages = sorted(set(wave_pages))

print("Olas encontradas:")
for w in wave_pages:
    print(w)

# =========================
# 2. entrar a cada ola y buscar ZIP de Stata
# =========================

stata_links = []

for page in wave_pages:

    print(f"\nRevisando {page}")

    try:
        html = requests.get(page, headers=headers, timeout=20).text
        soup = BeautifulSoup(html, "html.parser")

        for a in soup.find_all("a", href=True):

            href = a["href"]
            text = a.get_text(" ", strip=True).lower()

            full = urljoin(page, href)

            # queremos ZIPs relacionados con Stata
            if (
                ".zip" in href.lower()
                and (
                    "stata" in href.lower()
                    or "dta" in href.lower()
                    or "stata" in text
                )
            ):
                stata_links.append(full)

    except Exception as e:
        print("Error:", e)

# limpiar duplicados
stata_links = sorted(set(stata_links))

print("\nZIPs Stata encontrados:\n")

for l in stata_links:
    print(l)

Olas encontradas:
https://www.latinobarometro.org/latinobarometro-1995
https://www.latinobarometro.org/latinobarometro-1996
https://www.latinobarometro.org/latinobarometro-1997
https://www.latinobarometro.org/latinobarometro-1998
https://www.latinobarometro.org/latinobarometro-2000
https://www.latinobarometro.org/latinobarometro-2001
https://www.latinobarometro.org/latinobarometro-2002
https://www.latinobarometro.org/latinobarometro-2003
https://www.latinobarometro.org/latinobarometro-2004
https://www.latinobarometro.org/latinobarometro-2005
https://www.latinobarometro.org/latinobarometro-2006
https://www.latinobarometro.org/latinobarometro-2007
https://www.latinobarometro.org/latinobarometro-2008
https://www.latinobarometro.org/latinobarometro-2009
https://www.latinobarometro.org/latinobarometro-2010
https://www.latinobarometro.org/latinobarometro-2011
https://www.latinobarometro.org/latinobarometro-2013
https://www.latinobarometro.org/latinobarometro-2015
https://www.latinobarometro.org/latinobarometro-2016
https://www.latinobarometro.org/latinobarometro-2017
https://www.latinobarometro.org/latinobarometro-2018
https://www.latinobarometro.org/latinobarometro-2020
https://www.latinobarometro.org/latinobarometro-2023
https://www.latinobarometro.org/latinobarometro-2024

Revisando https://www.latinobarometro.org/latinobarometro-1995

Revisando https://www.latinobarometro.org/latinobarometro-1996

Revisando https://www.latinobarometro.org/latinobarometro-1997

Revisando https://www.latinobarometro.org/latinobarometro-1998

Revisando https://www.latinobarometro.org/latinobarometro-2000

Revisando https://www.latinobarometro.org/latinobarometro-2001

Revisando https://www.latinobarometro.org/latinobarometro-2002

Revisando https://www.latinobarometro.org/latinobarometro-2003

Revisando https://www.latinobarometro.org/latinobarometro-2004

Revisando https://www.latinobarometro.org/latinobarometro-2005

Revisando https://www.latinobarometro.org/latinobarometro-2006

Revisando https://www.latinobarometro.org/latinobarometro-2007

Revisando https://www.latinobarometro.org/latinobarometro-2008

Revisando https://www.latinobarometro.org/latinobarometro-2009

Revisando https://www.latinobarometro.org/latinobarometro-2010

Revisando https://www.latinobarometro.org/latinobarometro-2011

Revisando https://www.latinobarometro.org/latinobarometro-2013

Revisando https://www.latinobarometro.org/latinobarometro-2015

Revisando https://www.latinobarometro.org/latinobarometro-2016

Revisando https://www.latinobarometro.org/latinobarometro-2017

Revisando https://www.latinobarometro.org/latinobarometro-2018

Revisando https://www.latinobarometro.org/latinobarometro-2020

Revisando https://www.latinobarometro.org/latinobarometro-2023

Revisando https://www.latinobarometro.org/latinobarometro-2024

ZIPs Stata encontrados:

https://www.latinobarometro.org/documents/LAT-1995/latinobarometro-1995-dta.zip
https://www.latinobarometro.org/documents/LAT-1996/latinobarometro-1996-dta.zip
https://www.latinobarometro.org/documents/LAT-1997/latinobarometro-1997-dta.zip
https://www.latinobarometro.org/documents/LAT-1998/latinobarometro-1998-dta.zip
https://www.latinobarometro.org/documents/LAT-2000/latinobarometro-2000-dta.zip
https://www.latinobarometro.org/documents/LAT-2001/latinobarometro-2001-dta.zip
https://www.latinobarometro.org/documents/LAT-2002/latinobarometro-2002-dta.zip
https://www.latinobarometro.org/documents/LAT-2003/latinobarometro-2003-dta.zip
https://www.latinobarometro.org/documents/LAT-2004/latinobarometro-2004-dta.zip
https://www.latinobarometro.org/documents/LAT-2005/latinobarometro-2005-dta.zip
https://www.latinobarometro.org/documents/LAT-2006/latinobarometro-2006-dta.zip
https://www.latinobarometro.org/documents/LAT-2007/latinobarometro-2007-dta.zip
https://www.latinobarometro.org/documents/LAT-2008/latinobarometro-2008-dta.zip
https://www.latinobarometro.org/documents/LAT-2009/latinobarometro-2009-dta.zip
https://www.latinobarometro.org/documents/LAT-2010/latinobarometro-2010-dta.zip
https://www.latinobarometro.org/documents/LAT-2011/latinobarometro-2011-dta.zip
https://www.latinobarometro.org/documents/LAT-2013/latinobarometro-2013-dta.zip
https://www.latinobarometro.org/documents/LAT-2015/latinobarometro-2015-dta.zip
https://www.latinobarometro.org/documents/LAT-2016/latinobarometro2016-dta.zip
https://www.latinobarometro.org/documents/LAT-2017/latinobarometro2017-dta.zip
https://www.latinobarometro.org/documents/LAT-2018/latinobarometro-2018-eng-stata-v20190303.zip
https://www.latinobarometro.org/documents/LAT-2018/latinobarometro-2018-esp-dta-v20190303.zip
https://www.latinobarometro.org/documents/LAT-2020/latinobarometro-2020-eng-stata-v1-0.zip
https://www.latinobarometro.org/documents/LAT-2020/latinobarometro-2020-esp-stata-v1-0.zip
https://www.latinobarometro.org/documents/LAT-2023/latinobarometro-2023-stata-v1-0.zip
https://www.latinobarometro.org/documents/LAT-2024/latinobarometro-2024-stata-v20250817.zip

In [4]:
import requests

import shutil
import os

# borrar carpeta rota
shutil.rmtree("latinobarometro", ignore_errors=True)

# recrear
os.makedirs("latinobarometro", exist_ok=True)

for link in stata_links:

    filename = link.split("/")[-1]
    filepath = os.path.join("latinobarometro", filename)

    print("Descargando:", filename)

    r = requests.get(link)

    with open(filepath, "wb") as f:
        f.write(r.content)

Descargando: latinobarometro-1995-dta.zip
Descargando: latinobarometro-1996-dta.zip
Descargando: latinobarometro-1997-dta.zip
Descargando: latinobarometro-1998-dta.zip
Descargando: latinobarometro-2000-dta.zip
Descargando: latinobarometro-2001-dta.zip
Descargando: latinobarometro-2002-dta.zip
Descargando: latinobarometro-2003-dta.zip
Descargando: latinobarometro-2004-dta.zip
Descargando: latinobarometro-2005-dta.zip
Descargando: latinobarometro-2006-dta.zip
Descargando: latinobarometro-2007-dta.zip
Descargando: latinobarometro-2008-dta.zip
Descargando: latinobarometro-2009-dta.zip
Descargando: latinobarometro-2010-dta.zip
Descargando: latinobarometro-2011-dta.zip
Descargando: latinobarometro-2013-dta.zip
Descargando: latinobarometro-2015-dta.zip
Descargando: latinobarometro2016-dta.zip
Descargando: latinobarometro2017-dta.zip
Descargando: latinobarometro-2018-eng-stata-v20190303.zip
Descargando: latinobarometro-2018-esp-dta-v20190303.zip
Descargando: latinobarometro-2020-eng-stata-v1-0.zip
Descargando: latinobarometro-2020-esp-stata-v1-0.zip
Descargando: latinobarometro-2023-stata-v1-0.zip
Descargando: latinobarometro-2024-stata-v20250817.zip

In [5]:
!mkdir -p latinobarometro/unzipped

!find latinobarometro -name "*.zip" -exec unzip -o {} -d latinobarometro/unzipped \;

Archive:  latinobarometro/latinobarometro-2007-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2007_eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2007_esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2007_datos_esp_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2007_datos_eng_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2001-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2001_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2001_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2001_datos_esp_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2001_datos_english_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2015-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_Questionnaire_2015_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2015_Eng.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2015_Esp.dta
  inflating: latinobarometro/unzipped/Latinobarometro_Cuestionario_2015_Esp.pdf
Archive:  latinobarometro/latinobarometro-2023-stata-v1-0.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2023_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2023_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2023_Eng_Stata_v1_0.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2023_Esp_Stata_v1_0.dta
Archive:  latinobarometro/latinobarometro-2020-eng-stata-v1-0.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2020_Eng_Stata_v1_0.dta
Archive:  latinobarometro/latinobarometro-2018-eng-stata-v20190303.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2018_Eng_Stata_v20190303.dta
Archive:  latinobarometro/latinobarometro-2002-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2002_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2002_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2002_datos_eng_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2002_datos_esp_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro2017-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro2017Eng_v20180117.dta
  inflating: latinobarometro/unzipped/Latinobarometro2017Esp_v20180117.dta
  inflating: latinobarometro/unzipped/Latinobarometro2017_Cuestionario_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro2017_Questionnaire_Eng.pdf
Archive:  latinobarometro/latinobarometro-2013-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro2013Eng.dta
  inflating: latinobarometro/unzipped/Latinobarometro2013.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2013_cuestionario.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2013_questionnaire.pdf
Archive:  latinobarometro/latinobarometro-2010-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2010_eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2010_esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2010_datos_esp_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2010_datos_eng_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro2016-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro2016Eng_v20170205.dta
  inflating: latinobarometro/unzipped/Latinobarometro2016EngQuestionnaire.docx
  inflating: latinobarometro/unzipped/Latinobarometro2016Esp_v20170205.dta
  inflating: latinobarometro/unzipped/Latinobarometro2016EspCuestionario.docx
Archive:  latinobarometro/latinobarometro-2020-esp-stata-v1-0.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2020_Esp_Stata_v1_0.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2020_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2020_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2020_Eng_Stata_v1_0.dta
Archive:  latinobarometro/latinobarometro-2011-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2011_esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2011_eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2011_eng.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2011_esp.dta
Archive:  latinobarometro/latinobarometro-2024-stata-v20250817.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2024_Stata_eng_v20250817.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2024_Stata_esp_v20250817.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2024_Cuestionario_esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2024_Cuestionario_eng.pdf
Archive:  latinobarometro/latinobarometro-2018-esp-dta-v20190303.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2018_Esp_Stata_v20190303.dta
Archive:  latinobarometro/latinobarometro-1996-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_1996_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_1996_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_1996_datos_esp_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_1996_datos_english_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-1997-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_1997_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_1997_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_1997_datos_esp_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_1997_datos_english_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-1995-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_1995_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_1995_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_1995_datos_esp_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_1995_data_english_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2009-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2009_eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2009_esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2009_datos_eng_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2009_datos_esp_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2006-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2006_eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2006_esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2006_datos_eng_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2006_datos_esp_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2004-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2004_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2004_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2004_datos_eng_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2004_datos_esp_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-1998-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_1998_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_1998_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_1998_datos_english_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_1998_datos_esp_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2000-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2000_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2000_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2000_datos_esp_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2000_datos_eng_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2005-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2005_esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2005_eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2005_datos_esp_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2005_datos_eng_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2008-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2008_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2008_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2008_datos_eng_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2008_datos_esp_v2014_06_27.dta
Archive:  latinobarometro/latinobarometro-2003-dta.zip
  inflating: latinobarometro/unzipped/Latinobarometro_2003_Esp.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2003_Eng.pdf
  inflating: latinobarometro/unzipped/Latinobarometro_2003_datos_eng_v2014_06_27.dta
  inflating: latinobarometro/unzipped/Latinobarometro_2003_datos_esp_v2014_06_27.dta

In [6]:
# =========================
# mapeo armonizado
# =========================

varmap = {

    # ---------------------------------
    # satisfacción con la vida
    # ---------------------------------

    "life_satisfaction": {

        1997: "nsp10",
        2000: "P8ST",
        2001: "p41st",
        2003: "p19st",
        2004: "p1st",
        2005: "p1st",
        2006: "p1st_a",
        2007: "p1st",
        2008: "p27st",
        2009: "p1st",
        2010: "P1ST",
        2011: "P1ST",
        2013: "P1ST",
        2015: "P1ST",
        2016: "P1ST",
        2017: "P1ST",
        2018: "P1STC",
        2020: "p1st",
        2023: "P1ST",
        2024: "P1ST"
    },


    # ---------------------------------
    # situación económica actual del país
    # ---------------------------------

    "econ_country": {

        1995: "p1",
        1996: "p1",
        1997: "sp1",
        1998: "sp1",
        2000: "P1ST",
        2001: "p1st",
        2002: "p2sta",
        2003: "p1st",
        2004: "p2st",
        2005: "p2st",
        2006: "p2st",
        2007: "p100st",
        2008: "p4st",
        2009: "p3st_a",
        2010: "P3ST_A",
        2011: "P3ST_A",
        2013: "P3STGBS",
        2015: "P3STGBS",
        2016: "P4STGBS",
        2017: "P4STGBSC",
        2018: "P6STGBSC",
        2020: "p4stgbs",
        2023: "P5STGBS",
        2024: "P6STGBS"
    },

    # ---------------------------------
    # confianza interpersonal
    # ---------------------------------

    "trust_people": {

        1996: "p12",
        1997: "sp21",
        1998: "sp20",
        2000: "P17ST",
        2001: "p42st",
        2002: "p29st",
        2003: "p20st",
        2004: "p43st",
        2005: "p14st",
        2006: "p45st",
        2007: "p23st",
        2008: "p21wvsst",
        2009: "p58st",
        2010: "P55ST",
        2011: "P25ST",
        2013: "P29STGBS",
        2015: "P15STGBS",
        2016: "P12STGBS",
        2017: "P13STGBS",
        2018: "P11STGBS",
        2020: "p9stgbs",
        2023: "P9STGBS",
        2024: "P10STGBS"
    },

    # ---------------------------------
    # ciudad
    # ---------------------------------

    "city": {
        1997: "ciudad",
        2000: "ciudad",
        2001: "ciudad",
        2003: "ciudad",
        2004: "Ciudad",
        2005: "ciudad",
        2006: "ciudad",
        2007: "ciudad",
        2008: "ciudad",
        2009: "ciudad",
        2010: "ciudad",
        2011: "ciudad",
        2013: "ciudad",
        2015: "ciudad",
        2016: "ciudad",
        2017: "ciudad",
        2018: "CIUDAD",
        2020: "ciudad",
        2023: "ciudad",
        2024: "CIUDAD"
    },

    # ---------------------------------
    # interés en política
    # ---------------------------------

    "interest_politics": {

        1995: "p62",
        1996: "p64",
        1997: "sp41",
        1998: "sp36",
        2000: "P63ST",
        2001: "p56st",
        2003: "p61st",
        2004: "p29st",
        2005: "p37st",
        2007: "p59st",
        2009: "p32st",
        2010: "P23ST",
        2013: "P20STGBS",
        2020: "p46stgbs",
        2023: "P40STGBS",
        2024: "P36STGBS",

    },

    # ---------------------------------
    # sexo
    # ---------------------------------

    "sex": {

        1995: "s1",
        1996: "s1",
        1997: "s1",
        1998: "s1",
        2000: "S1",
        2001: "s1",
        2002: "s1",
        2003: "s1",
        2004: "s1",
        2005: "s6",
        2006: "s6",
        2007: "s10",
        2008: "s8",
        2009: "s5",
        2010: "S7",
        2011: "S16",
        2013: "S10",
        2015: "S12",
        2016: "sexo",
        2017: "sexo",
        2018: "SEXO",
        2020: "sexo",
        2023: "sexo",
        2024: "SEXO"
    },

    # ---------------------------------
    # edad
    # ---------------------------------

    "age": {

        1995: "s2",
        1996: "s2",
        1997: "s2",
        1998: "s2",
        2000: "S2",
        2001: "s2",
        2002: "s2",
        2003: "s2",
        2004: "s2",
        2005: "s7",
        2006: "s7",
        2007: "s11",
        2008: "s9",
        2009: "s6",
        2010: "S8",
        2011: "S17",
        2013: "S11",
        2015: "S13",
        2016: "edad",
        2017: "edad",
        2018: "EDAD",
        2020: "edad",
        2023: "edad",
        2024: "EDAD"
    },

    # ---------------------------------
    # estado civil
    # ---------------------------------

    "civil_status": {

        1995: "s6",
        1996: "s5",
        1997: "s5",
        1998: "s5",
        2000: "S4",
        2001: "s4",
        2002: "s4",
        2003: "s4",
        2004: "s4",
        2005: "s9",
        2006: "s9",
        2007: "s13",
        2008: "s3",
        2009: "s3",
        2010: "S5",
        2011: "S15",
        2013: "S9",
        2015: "S11",
        2016: "S5",
        2017: "S6",
        2018: "S23"
    },

    # ---------------------------------
    # izquierda-derecha
    # ---------------------------------

    "left_right": {

        1995: "p31",
        1996: "p38",
        1997: "sp56",
        1998: "sp52",
        2000: "P52ST",
        2001: "p54st",
        2002: "p64st",
        2003: "p60st",
        2004: "p87st",
        2005: "p34st",
        2006: "p47st",
        2007: "p67st",
        2008: "p56st",
        2009: "p69st",
        2010: "P60ST",
        2011: "P76ST",
        2013: "P41ST",
        2015: "P27ST",
        2016: "P17ST",
        2017: "P19STC",
        2018: "P22ST",
        2020: "p18st",
        2023: "P16ST",
        2024: "P16ST"
    },


    # ---------------------------------
    # país
    # ---------------------------------

    "country": {

        1995: "pais",
        1996: "pais",
        1997: "idenpa",
        1998: "idenpa",
        2000: "idenpa",
        2001: "idenpa",
        2002: "idenpa",
        2003: "idenpa",
        2004: "idenpa",
        2005: "idenpa",
        2006: "idenpa",
        2007: "idenpa",
        2008: "idenpa",
        2009: "idenpa",
        2010: "idenpa",
        2011: "idenpa",
        2013: "idenpa",
        2015: "idenpa",
        2016: "idenpa",
        2017: "idenpa",
        2018: "IDENPA",
        2020: "idenpa",
        2023: "idenpa",
        2024: "IDENPA"
    },

    # ---------------------------------
    # educación
    # ---------------------------------

"education": {

    1995: "s17",
    1996: "s14",
    1997: "s10",
    1998: "s11",
    2000: "S6",
    2001: "s6",
    2002: "s6",
    2003: "s6",
    2004: "s6",
    2005: "s11",
    2006: "s11",
    2007: "s15",
    2008: "s15",
    2009: "s12",
    2010: "S14",
    2011: "S21",
    2013: "S17",
    2015: "S19",
    2016: "S13",
    2017: "S14",
    2018: "S10",
    2020: "s16",
    2023: "S11",
    2024: "S11"
},

# ---------------------------------
# twitter
# ---------------------------------

"twitter": {

    2009: "S25_E",
    2010: "S27_E",
    2011: "S33ST_BE",
    2013: "P83TNCE",
    2015: "S10M_E",
    2016: "S15M_D",
    2017: "S16M_D",
    2018: "S12M.D",
    2020: "s19m_04",
    2023: "S14M_D",
    2024: "S14M.4"

},

# ---------------------------------
# Voto
# ---------------------------------
"vote": {

    1995: "p33",
    1996: "p40",
    1997: "sp58",
    1998: "sp53",
    2000: "P54ST",
    2001: "p55st",
    2002: "p45st",
    2003: "p54st",
    2004: "p30st",
    2005: "p48st",
    2006: "p38st",
    2007: "p64st",
    2008: "p61st",
    2009: "p35st",
    2010: "P29ST",
    2011: "P38ST",
    2013: "P22TGBSM",
    2015: "P23TGBSM",
    2016: "P15STGBS",
    2017: "P16STGBS",
    2018: "P21STGBS.A",
    2020: "P50STGBS_A",
    2023: "P43STGBS_A",
    2024: "P39STGBS.A"
}

}

In [7]:
import pandas as pd
import numpy as np
from pathlib import Path

BASE = Path("latinobarometro/unzipped")

# =========================
# buscar archivos
# =========================

dta_files = sorted([
    f for f in BASE.rglob("*.dta")
    if "eng" not in f.name.lower()
])

# =========================
# detectar ola
# =========================

def detect_wave(path):

    m = re.search(r"(19|20)\d{2}", path.name)

    if m:
        return int(m.group())

    return np.nan

# =========================
# verificar SOLO faltantes
# =========================

for file in dta_files:

    try:

        wave = detect_wave(file)

        # leer pocas filas
        tmp_reader = pd.read_stata(
            file,
            convert_categoricals=False,
            iterator=True
        )

        tmp = tmp_reader.read(5)

        existing_cols = set(tmp.columns)

        missing = []

        # -------------------------
        # revisar varmap
        # -------------------------

        for new_name, mapping in varmap.items():

            if wave not in mapping:
                continue

            old_var = mapping[wave]

            if old_var not in existing_cols:

                missing.append(
                    f"{new_name} -> {old_var}"
                )

        # -------------------------
        # imprimir sólo si faltan
        # -------------------------

        if len(missing) > 0:

            print("\n" + "="*60)
            print(f"{file.name} | wave={wave}")

            for m in missing:
                print("FALTA:", m)

        del tmp
        del tmp_reader

    except Exception as e:

        print(f"\nERROR en {file.name}")
        print(e)

In [8]:
# =========================================
# buscar la variable de Twitter por año
# =========================================

social_blocks = {
    2009: "S25",
    2010: "S27",
    2011: "S33ST",
    2013: "P83TNC",
    2015: "S10M",
    2016: "S15M",
    2017: "S16M",
    2018: "S12M",
    2020: "S19M",
    2023: "S14M"
}

for file in dta_files:

    wave = detect_wave(file)

    if wave not in social_blocks:
        continue

    bloque = social_blocks[wave]

    try:

        reader = pd.read_stata(
            file,
            convert_categoricals=False,
            iterator=True
        )

        var_labels = reader.variable_labels()

        print("\n" + "="*70)
        print(file.name, "| wave =", wave)

        for var, label in var_labels.items():

            if var.upper().startswith(bloque.upper()):

                if "twitter" in str(label).lower():

                    print("VARIABLE:", var)
                    print("LABEL:", label)

    except Exception as e:

        print("\nERROR:", file.name)
        print(e)

======================================================================
Latinobarometro2013.dta | wave = 2013
VARIABLE: P83TNCE
LABEL: P83TNCE Uso redes sociales: Twitter

======================================================================
Latinobarometro2016Esp_v20170205.dta | wave = 2016
VARIABLE: S15M_D
LABEL: S15M_D Uso redes sociales: Twitter

======================================================================
Latinobarometro2017Esp_v20180117.dta | wave = 2017
VARIABLE: S16M_D
LABEL: S16M_D Uso redes sociales: Twitter

======================================================================
Latinobarometro_2009_datos_esp_v2014_06_27.dta | wave = 2009
VARIABLE: S25_E
LABEL: Servicios de Redes Sociales utilizados: Twitter

======================================================================
Latinobarometro_2010_datos_esp_v2014_06_27.dta | wave = 2010
VARIABLE: S27_E
LABEL: Servicios de Redes Sociales utilizados: Twitter

======================================================================
Latinobarometro_2011_esp.dta | wave = 2011
VARIABLE: S33ST_BE
LABEL: Servicios de Redes Sociales utilizados: Twitter

======================================================================
Latinobarometro_2015_Esp.dta | wave = 2015
VARIABLE: S10M_E
LABEL: S10M_E Uso redes sociales: Twitter

======================================================================
Latinobarometro_2018_Esp_Stata_v20190303.dta | wave = 2018
VARIABLE: S12M.D
LABEL: S12M.D Redes sociales que utiliza: Twitter

======================================================================
Latinobarometro_2020_Esp_Stata_v1_0.dta | wave = 2020
VARIABLE: s19m_04
LABEL: S19M_04 Uso redes sociales: Twitter

======================================================================
Latinobarometro_2023_Esp_Stata_v1_0.dta | wave = 2023
VARIABLE: S14M_D
LABEL: S14M.D Servicios de redes sociales que usa: Twitter

In [9]:
def detect_id(df):

    for c in [
        "IDNUM",
        "idnum",
        "Idnum",
        "id_num",
        "NUMINVES",
        "numinves",
        "folio",
        "FOLIO",
        "numero",
        "NUMERO"
    ]:

        if c in df.columns:
            return c

    return None

# =========================
# merge final
# =========================

master = pd.DataFrame()

for file in dta_files:

    try:

        wave = detect_wave(file)

        print(f"Cargando {file.name} | wave={wave}")

        # -------------------------
        # leer nombres columnas
        # -------------------------

        tmp_reader = pd.read_stata(
            file,
            convert_categoricals=False,
            iterator=True
        )

        tmp = tmp_reader.read(5)

        # normalizar nombres
        tmp.columns = (
            tmp.columns
            .str.strip()
        )

        existing_cols = set(tmp.columns)

        # -------------------------
        # detectar ID
        # -------------------------

        id_col = detect_id(tmp)

        if id_col is None:

            print("  -> no se encontró ID")
            continue

        # -------------------------
        # variables disponibles
        # -------------------------

        wave_vars = {}

        for new_name, mapping in varmap.items():

            if wave not in mapping:
                continue

            old_var = mapping[wave]

            if old_var in existing_cols:

                wave_vars[new_name] = old_var

        # columnas a leer
        cols_to_read = list(
            set(wave_vars.values()) | {id_col}
        )

        # -------------------------
        # cargar datos reales
        # -------------------------

        df = pd.read_stata(
            file,
            columns=cols_to_read,
            convert_categoricals=False
        )

        # normalizar columnas
        df.columns = (
            df.columns
            .str.strip()
        )

        # -------------------------
        # crear ID
        # -------------------------

        df["id"] = df[id_col].astype(str)

        # -------------------------
        # renombrar variables
        # -------------------------

        rename_dict = {
            old: new
            for new, old in wave_vars.items()
        }

        df = df.rename(columns=rename_dict)

        # -------------------------
        # agregar ola
        # -------------------------

        df["wave"] = wave

        # -------------------------
        # conservar columnas finales
        # -------------------------

        keep_cols = [
            "id",
            "wave",
            "country",
            "city",
            "life_satisfaction",
            "interest_politics",
            "sex",
            "age",
            "civil_status",
            "left_right",
            "education",
            "econ_country",
            "trust_people",
            "twitter",
            "vote"
        ]

        # crear faltantes
        for c in keep_cols:

            if c not in df.columns:
                df[c] = np.nan

        df = df[keep_cols]

        # -------------------------
        # append
        # -------------------------

        master = pd.concat(
            [master, df],
            ignore_index=True,
            sort=False
        )

        del df
        del tmp
        del tmp_reader

    except Exception as e:

        print(f"ERROR en {file.name}")
        print(e)

Cargando Latinobarometro2013.dta | wave=2013
Cargando Latinobarometro2016Esp_v20170205.dta | wave=2016
Cargando Latinobarometro2017Esp_v20180117.dta | wave=2017
Cargando Latinobarometro_1995_datos_esp_v2014_06_27.dta | wave=1995
Cargando Latinobarometro_1996_datos_esp_v2014_06_27.dta | wave=1996
Cargando Latinobarometro_1997_datos_esp_v2014_06_27.dta | wave=1997
Cargando Latinobarometro_1998_datos_esp_v2014_06_27.dta | wave=1998
Cargando Latinobarometro_2000_datos_esp_v2014_06_27.dta | wave=2000
Cargando Latinobarometro_2001_datos_esp_v2014_06_27.dta | wave=2001
Cargando Latinobarometro_2002_datos_esp_v2014_06_27.dta | wave=2002
Cargando Latinobarometro_2003_datos_esp_v2014_06_27.dta | wave=2003
Cargando Latinobarometro_2004_datos_esp_v2014_06_27.dta | wave=2004
Cargando Latinobarometro_2005_datos_esp_v2014_06_27.dta | wave=2005
Cargando Latinobarometro_2006_datos_esp_v2014_06_27.dta | wave=2006
Cargando Latinobarometro_2007_datos_esp_v2014_06_27.dta | wave=2007
Cargando Latinobarometro_2008_datos_esp_v2014_06_27.dta | wave=2008
Cargando Latinobarometro_2009_datos_esp_v2014_06_27.dta | wave=2009
Cargando Latinobarometro_2010_datos_esp_v2014_06_27.dta | wave=2010
Cargando Latinobarometro_2011_esp.dta | wave=2011
Cargando Latinobarometro_2015_Esp.dta | wave=2015
Cargando Latinobarometro_2018_Esp_Stata_v20190303.dta | wave=2018
Cargando Latinobarometro_2020_Esp_Stata_v1_0.dta | wave=2020
Cargando Latinobarometro_2023_Esp_Stata_v1_0.dta | wave=2023
Cargando Latinobarometro_2024_Stata_esp_v20250817.dta | wave=2024

# Redodificación

In [10]:
# =========================
# recodificar life_satisfaction
# =========================

conversion = {

    4: 1,  # para nada
    3: 2,  # no muy
    2: 3,  # bastante
    1: 4   # muy
}

master["life_satisfaction"] = (
    master["life_satisfaction"]
    .map(conversion)
)

# =========================
# recodificar interest_politics
# =========================

master["interest_politics"] = (
    master["interest_politics"]
    .replace(conversion)
)

# =========================
# recodificar sex
# =========================

conversion = {
    1: 1,  # hombre
    2: 0   # mujer
}

master["sex"] = (
    master["sex"]
    .map(conversion)
)

# =========================
# distancia al centro ideológico
# =========================

def convertir(val):

    try:

        num = float(val)

        # missings típicos latinobarómetro
        if num in [97, 98, 99, -1, -2, -6, -8]:
            return np.nan

        return num

    except:

        return np.nan

# convertir escala izquierda-derecha
master["left_right_scale"] = (
    master["left_right"]
    .apply(convertir)
)

# distancia al centro
master["left_right_distance"] = (
    np.abs(master["left_right_scale"] - 5)
)

master["polarization"]=master["left_right_distance"]

# =========================
# recodificar education
# =========================

# paso 1
master["education_num"] = pd.to_numeric(
    master["education"],
    errors="coerce"
)

# paso 2
def escalar_educacion(x):

    if pd.isna(x):
        return np.nan

    if x == 1:
        return 0  # sin estudios

    elif 2 <= x <= 13:
        return x - 1  # años reales

    elif x == 14:
        return 14  # universitario incompleto

    elif x == 15:
        return 16  # universitario completo

    elif x == 16:
        return 13  # técnico incompleto

    elif x == 17:
        return 14  # técnico completo

    else:
        return np.nan

# aplicar
master["education"] = (
    master["education_num"]
    .apply(escalar_educacion)
)


# =========================
# recodificar econ_country
# =========================

master["econ_country"] = pd.to_numeric(
    master["econ_country"],
    errors="coerce"
)

conversion_econ = {

    1: 5,  # muy buena
    2: 4,  # buena
    3: 3,  # regular
    4: 2,  # mala
    5: 1   # muy mala
}

master["econ_country"] = (
    master["econ_country"]
    .map(conversion_econ)
)

# =========================
# recodificar trust_people
# =========================

conversion = {

    1: 1,  # se puede confiar
    2: 0   # nunca suficientemente cuidadoso
}

master["trust_people"] = pd.to_numeric(
    master["trust_people"],
    errors="coerce"
)

master["trust_people"] = (
    master["trust_people"]
    .map(conversion)
)

# cualquier valor no mapeado -> NaN
master.loc[
    ~master["trust_people"].isin([0, 1]),
    "trust_people"
] = np.nan

master["twitter"] = np.where(
    master["twitter"] == 1,
    1,
    np.where(
        master["twitter"] == 0,
        0,
        np.nan
    )
)

sin_partido = {
    -7, -4, -3, -2, -1,
    94, 95, 96, 97
}

master["party_id"] = (
    (~master["vote"].isin(sin_partido))
    & (master["vote"].notna())
).astype(int)

In [11]:
master["left_right_scale"].unique()

array([ 6.,  2.,  5.,  7., nan,  0.,  3.,  4.,  9., 10.,  8.,  1.])

# EDA

In [12]:
master["interest_politics"] = master["interest_politics"].replace(-2, np.nan)
master["interest_politics"] = master["interest_politics"].replace(-1, np.nan)


master["age"] = master["age"].replace(-2, np.nan)

master["civil_status"] = master["civil_status"].replace(-2, np.nan)

master["left_right"] = master["left_right"].replace(
    [-8, 97],
    np.nan
)

master["vote"] = master["vote"].replace(
    [-7, -1],
    np.nan
)

In [13]:
cols=["life_satisfaction",

      "interest_politics",
      "left_right_distance",
      "party_id",

      "sex",
      "age",
      "education",
      "econ_country",
      "trust_people",
      "twitter",
      ]

In [14]:
master[cols].describe()

,life_satisfaction,interest_politics,left_right_distance,party_id,sex,age,education,econ_country,trust_people,twitter
count,412867.000000,317696.000000,387609.000000,489771.000000,489728.000000,489700.000000,474957.000000,483727.000000,466816.000000,226420.000000
mean,2.956671,2.009345,2.082764,0.397412,0.484263,40.156412,8.946905,2.576995,0.195253,0.095879
std,0.871374,0.965805,1.880417,0.489363,0.499753,16.511289,4.586588,0.933137,0.396395,0.294426
min,1.000000,1.000000,0.000000,0.000000,0.000000,15.000000,0.000000,1.000000,0.000000,0.000000
25%,2.000000,1.000000,0.000000,0.000000,0.000000,26.000000,6.000000,2.000000,0.000000,0.000000
50%,3.000000,2.000000,2.000000,0.000000,0.000000,38.000000,9.000000,3.000000,0.000000,0.000000
75%,4.000000,3.000000,4.000000,1.000000,1.000000,52.000000,12.000000,3.000000,0.000000,0.000000
max,4.000000,4.000000,5.000000,1.000000,1.000000,100.000000,16.000000,5.000000,1.000000,1.000000

In [15]:
master.groupby("wave")[cols].mean()

,life_satisfaction,interest_politics,left_right_distance,party_id,sex,age,education,econ_country,trust_people,twitter
wave,,,,,,,,,,
1995,NaN,2.028808,1.979335,0.487044,0.472554,38.732693,9.328120,2.503451,NaN,NaN
1996,NaN,1.950556,2.102504,0.403726,0.487400,39.284817,9.631889,2.344413,0.225252,NaN
1997,2.351060,2.099258,1.968332,0.357852,0.487280,39.078091,9.827562,2.569642,0.243657,NaN
1998,NaN,2.051801,1.977314,0.531208,0.486400,39.025639,10.014600,2.492197,0.232818,NaN
2000,2.365140,2.113045,1.964082,0.059486,0.486029,38.393724,9.943342,2.433088,0.158688,NaN
2001,2.920137,1.959501,2.145147,0.377781,0.489894,39.445565,8.788610,2.323397,0.198213,NaN
2002,NaN,NaN,2.276506,0.047320,0.483957,39.609712,8.532664,2.386877,0.211212,NaN
2003,3.068278,1.985185,2.172544,0.429518,0.487105,39.822630,8.285385,2.356523,0.190926,NaN
2004,2.897600,2.037793,2.036825,0.139256,0.491673,39.739138,8.309411,2.435680,0.187778,NaN
2005,2.957095,1.914768,2.183356,0.504747,0.490852,39.282564,7.942241,2.522436,0.196597,NaN
2006,3.029330,NaN,1.969466,0.515765,0.488682,40.149683,8.108992,2.780345,0.240726,NaN
2007,2.970551,2.015591,1.741416,0.432008,0.490746,40.391910,8.236850,2.887901,0.186458,NaN
2008,2.881377,NaN,1.768008,0.514928,0.483087,40.733151,8.400353,2.714881,0.230797,NaN
2009,2.979887,2.028952,1.909606,0.491670,0.479154,41.032349,8.293962,2.589027,0.237799,0.015646
2010,2.957853,1.941654,1.854251,0.433640,0.482214,40.864542,8.682574,2.650853,0.225629,0.006964
2011,2.988217,NaN,1.770970,0.508563,0.479410,40.117452,8.509206,2.757401,0.226070,0.062017
2013,3.050215,1.983737,2.067318,0.466222,0.485064,41.095486,8.814641,2.783440,0.189108,0.116666
2015,3.083573,NaN,2.271572,0.437630,0.484148,40.369630,8.985383,2.845897,0.172975,0.114646
2016,3.028138,NaN,2.316447,0.440952,0.483964,40.268610,9.103940,2.608394,0.169495,0.133934
2017,3.040243,NaN,2.219723,0.379406,0.478465,40.347970,9.231386,2.624857,0.143458,0.116040
2018,3.051716,NaN,2.223000,0.413383,0.479905,40.563651,9.259206,2.551734,0.146882,0.127747
2020,3.099995,1.976312,2.253109,0.363245,0.478470,40.998515,9.577843,2.461519,0.130941,0.130902
2023,3.126652,2.050160,2.357781,0.396355,0.474824,41.540120,9.906535,2.513984,0.166248,0.133038
2024,3.151256,2.047311,2.458175,0.397314,0.482669,41.772666,9.828719,2.625673,0.154540,0.119600

In [16]:
import pandas as pd

# Estadísticas descriptivas
desc = master[cols].agg(
    ['mean', 'std', 'min', 'max', 'count']
).T

desc.columns = ['Mean', 'SD', 'Min', 'Max', 'N']

rows = [
    ("\\midrule\n\\multicolumn{6}{l}{\\textit{Variable dependiente}} \\\\", None),
    ("Satisfacción con la vida", "life_satisfaction"),

    ("\\midrule\n\\multicolumn{6}{l}{\\textit{Variables principales}} \\\\", None),
    ("Interés por la política", "interest_politics"),
    ("Polarización ideológica", "left_right_distance"),
    ("Se identifica con un partido", "party_id"),

    ("\\midrule\n\\multicolumn{6}{l}{\\textit{Características sociodemográficas}} \\\\", None),
    ("Sexo (hombre)", "sex"),
    ("Edad", "age"),
    ("Nivel educativo", "education"),

    ("\\midrule\n\\multicolumn{6}{l}{\\textit{Variables actitudinales}} \\\\", None),
    ("Eval. de la sit. econ. del país", "econ_country"),
    ("Confianza interpersonal", "trust_people"),

    ("\\midrule\n\\multicolumn{6}{l}{\\textit{Redes sociales}} \\\\", None),
    ("Uso de Twitter/X", "twitter"),
]

latex = []
latex.append("\\begin{table}[htbp]")
latex.append("\\centering")
latex.append("\\caption{Estadísticas descriptivas}")
latex.append("\\label{tab:descriptivas}")
latex.append("\\begin{tabular}{lccccc}")
latex.append("\\toprule")
latex.append("Variable & Media & DE & Mín. & Máx. & N \\\\")
latex.append("\\midrule")

for label, var in rows:

    if var is None:
        latex.append(label)
        continue

    r = desc.loc[var]

    latex.append(
        f"{label} & "
        f"{r['Mean']:.2f} & "
        f"{r['SD']:.2f} & "
        f"{r['Min']:.2f} & "
        f"{r['Max']:.2f} & "
        f"{int(r['N']):,} \\\\"
    )

latex.append("\\bottomrule")
latex.append("\\end{tabular}")
latex.append("\\end{table}")

with open("descriptive_stats.tex", "w", encoding="utf-8") as f:
    f.write("\n".join(latex))

In [17]:
vars_avail = {
    "life_satisfaction": "Felicidad",
    "interest_politics": "Interés político",
    "left_right": "Polarización",
    "education": "Educación",
    "trust_people": "Confianza",
    "twitter": "Twitter"
}

availability = (
    master
    .groupby("wave")
    .agg(
        Observaciones=("wave", "size"),
        Paises=("country", "nunique")
    )
)

for var, label in vars_avail.items():
    availability[label] = (
        master
        .groupby("wave")[var]
        .apply(lambda x: 100 * x.notna().mean())
    )

availability = availability.round(1)

In [18]:
latex = availability.to_latex(
    caption="Disponibilidad de información por ola",
    label="tab:availability",
    float_format="%.1f",
    escape=False
)

with open("availability.tex", "w", encoding="utf-8") as f:
    f.write(latex)

# Estandarización

In [19]:
vars_z = [
    "left_right_distance", "life_satisfaction","interest_politics", "age" ,"education" , "econ_country"
    ]

for v in vars_z:
    master[f"{v}_z"] = np.nan

for wave in master["wave"].unique():
    mask = master["wave"] == wave
    for v in vars_z:
        if v in master.columns:
            s = master.loc[mask, v].astype(float)
            mean = s.mean(skipna=True)
            sd = s.std(skipna=True)
            master.loc[mask, f"{v}_z"] = (s - mean) / sd if sd not in [0, None] else np.nan

# Modelos

In [20]:
#Eliminamos España
master = master[master['country'] != 724]

In [36]:
import statsmodels.formula.api as smf
import pandas as pd
import numpy as np

# =========================
# base para regresión
# =========================

df_reg = master.copy()
#df_reg = df_reg[df_reg['wave'] > 2000]

# variables necesarias
vars_needed = [
    "life_satisfaction_z",
    "interest_politics_z",
    "left_right_distance_z",
    "age_z",
    "education_z",
    "econ_country_z",
    "sex",
    "trust_people",
    "wave",
    "city"
]

df_reg = df_reg[vars_needed].copy()

# convertir a numérico
for c in vars_needed:

    df_reg[c] = pd.to_numeric(
        df_reg[c],
        errors="coerce"
    )

# drop missing
df_reg = df_reg.dropna()

print(df_reg.shape)

# =========================
# regresión OLS
# errores clusterizados por ola
# =========================

model = smf.ols(

    formula="""
    life_satisfaction_z ~
    interest_politics_z +
    left_right_distance_z +
    age_z +
    education_z +
    econ_country_z +
    trust_people +
    sex

    """,

    data=df_reg

).fit(

    cov_type="cluster",

    cov_kwds={
        "groups": df_reg["city"]
    }
)

print(model.summary())

(192272, 10)
                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.037
Model:                             OLS   Adj. R-squared:                  0.037
Method:                  Least Squares   F-statistic:                     502.7
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):               0.00
Time:                         14:28:11   Log-Likelihood:            -2.7032e+05
No. Observations:               192272   AIC:                         5.407e+05
Df Residuals:                   192264   BIC:                         5.407e+05
Df Model:                            7
Covariance Type:               cluster
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                -0.0087      0.015     -0.595      0.552      -0.037       0.020
interest_politics_z       0.0192      0.004      4.670      0.000       0.011       0.027
left_right_distance_z     0.0407      0.004      9.382      0.000       0.032       0.049
age_z                    -0.0450      0.004    -11.881      0.000      -0.052      -0.038
education_z               0.0479      0.006      7.766      0.000       0.036       0.060
econ_country_z            0.1587      0.004     41.643      0.000       0.151       0.166
trust_people              0.1247      0.014      8.764      0.000       0.097       0.153
sex                      -0.0031      0.005     -0.642      0.521      -0.012       0.006
==============================================================================
Omnibus:                     9659.260   Durbin-Watson:                   1.683
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5963.539
Skew:                          -0.300   Prob(JB):                         0.00
Kurtosis:                       2.380   Cond. No.                         3.27
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [39]:
import statsmodels.formula.api as smf
import pandas as pd
import numpy as np

# =========================
# base para regresión
# =========================

df_reg = master.copy()

vars_needed = [
    "life_satisfaction_z",
    "interest_politics_z",
    "left_right_distance_z",
    "age_z",
    "education_z",
    "wave",
    "econ_country_z",
    "sex",
    "trust_people",
    "city"
]

df_reg = df_reg[vars_needed].copy()

# convertir a numérico
for c in vars_needed:

    df_reg[c] = pd.to_numeric(
        df_reg[c],
        errors="coerce"
    )

# eliminar missing
df_reg = df_reg.dropna()

print(df_reg.shape)

# =========================
# OLS con efectos fijos por ola
# =========================

model = smf.ols(

    formula="""
    life_satisfaction_z ~
    interest_politics_z +
    left_right_distance_z +
    age_z +
    education_z +
    econ_country_z +
    sex +
    trust_people +
    C(wave)
    """,

    data=df_reg

).fit(

    cov_type="cluster",

    cov_kwds={
        "groups": df_reg["city"]
    }
)

print(model.summary())

(192272, 10)
                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.037
Model:                             OLS   Adj. R-squared:                  0.037
Method:                  Least Squares   F-statistic:                     203.4
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):               0.00
Time:                         14:38:21   Log-Likelihood:            -2.7031e+05
No. Observations:               192272   AIC:                         5.407e+05
Df Residuals:                   192252   BIC:                         5.409e+05
Df Model:                           19
Covariance Type:               cluster
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                -0.0144      0.051     -0.284      0.777      -0.114       0.085
C(wave)[T.2000]           0.0012      0.039      0.030      0.976      -0.075       0.078
C(wave)[T.2001]           0.0039      0.052      0.075      0.940      -0.097       0.105
C(wave)[T.2003]          -0.0011      0.052     -0.021      0.984      -0.103       0.101
C(wave)[T.2004]           0.0104      0.051      0.205      0.837      -0.089       0.110
C(wave)[T.2005]           0.0077      0.051      0.150      0.880      -0.093       0.108
C(wave)[T.2007]           0.0075      0.052      0.144      0.885      -0.094       0.109
C(wave)[T.2009]          -0.0233      0.053     -0.441      0.659      -0.127       0.080
C(wave)[T.2010]          -0.0054      0.055     -0.098      0.922      -0.114       0.103
C(wave)[T.2013]           0.0232      0.052      0.449      0.653      -0.078       0.125
C(wave)[T.2020]           0.0102      0.053      0.193      0.847      -0.093       0.113
C(wave)[T.2023]           0.0182      0.053      0.344      0.731      -0.085       0.122
C(wave)[T.2024]           0.0129      0.053      0.243      0.808      -0.091       0.117
interest_politics_z       0.0193      0.004      4.641      0.000       0.011       0.027
left_right_distance_z     0.0408      0.004      9.407      0.000       0.032       0.049
age_z                    -0.0451      0.004    -11.925      0.000      -0.053      -0.038
education_z               0.0478      0.006      7.789      0.000       0.036       0.060
econ_country_z            0.1586      0.004     41.996      0.000       0.151       0.166
sex                      -0.0030      0.005     -0.631      0.528      -0.012       0.006
trust_people              0.1262      0.013      9.371      0.000       0.100       0.153
==============================================================================
Omnibus:                     9502.324   Durbin-Watson:                   1.683
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5915.470
Skew:                          -0.300   Prob(JB):                         0.00
Kurtosis:                       2.384   Cond. No.                         17.6
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [40]:
import statsmodels.formula.api as smf
import pandas as pd
import numpy as np

# =========================
# base para regresión
# =========================

df_reg = master.copy()

vars_needed = [
    "life_satisfaction_z",
    "interest_politics_z",
    "left_right_distance_z",
    "age_z",
    "education_z",
    "wave",
    "country",
    "city",
    "econ_country_z",
    "sex",
    "trust_people"

]

df_reg = df_reg[vars_needed].copy()

# convertir numéricas
for c in [
    "life_satisfaction_z",
    "interest_politics_z",
    "left_right_distance_z",
    "age_z",
    "education_z"
]:

    df_reg[c] = pd.to_numeric(
        df_reg[c],
        errors="coerce"
    )

# eliminar missing
df_reg = df_reg.dropna()

print(df_reg.shape)

# =========================
# OLS con FE de ola y país
# =========================

model = smf.ols(

    formula="""
    life_satisfaction_z ~
    interest_politics_z +
    left_right_distance_z +
    age_z +
    education_z +
    econ_country_z +
    sex +
    trust_people +
    C(wave) +
    C(country)
    """,

    data=df_reg

).fit(

    cov_type="cluster",

    cov_kwds={
        "groups": df_reg["city"]
    }
)

print(model.summary())

(192272, 11)
                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.085
Model:                             OLS   Adj. R-squared:                  0.085
Method:                  Least Squares   F-statistic:                     250.7
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):               0.00
Time:                         14:39:45   Log-Likelihood:            -2.6535e+05
No. Observations:               192272   AIC:                         5.308e+05
Df Residuals:                   192235   BIC:                         5.312e+05
Df Model:                           36
Covariance Type:               cluster
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                -0.1142      0.025     -4.481      0.000      -0.164      -0.064
C(wave)[T.2000]           0.0144      0.033      0.432      0.665      -0.051       0.080
C(wave)[T.2001]           0.0183      0.025      0.743      0.457      -0.030       0.066
C(wave)[T.2003]           0.0345      0.027      1.298      0.194      -0.018       0.087
C(wave)[T.2004]           0.0143      0.024      0.602      0.547      -0.032       0.061
C(wave)[T.2005]           0.0157      0.024      0.647      0.518      -0.032       0.063
C(wave)[T.2007]           0.0175      0.027      0.644      0.519      -0.036       0.071
C(wave)[T.2009]          -0.0142      0.027     -0.516      0.606      -0.068       0.040
C(wave)[T.2010]          -0.0026      0.032     -0.082      0.934      -0.064       0.059
C(wave)[T.2013]           0.0171      0.027      0.636      0.525      -0.036       0.070
C(wave)[T.2020]           0.0147      0.029      0.507      0.612      -0.042       0.071
C(wave)[T.2023]           0.0266      0.031      0.861      0.389      -0.034       0.087
C(wave)[T.2024]           0.0204      0.031      0.667      0.504      -0.039       0.080
C(country)[T.68]         -0.2867      0.027    -10.789      0.000      -0.339      -0.235
C(country)[T.76]         -0.1546      0.018     -8.433      0.000      -0.191      -0.119
C(country)[T.152]        -0.1428      0.031     -4.664      0.000      -0.203      -0.083
C(country)[T.170]         0.3077      0.023     13.581      0.000       0.263       0.352
C(country)[T.188]         0.4719      0.022     21.922      0.000       0.430       0.514
C(country)[T.214]         0.2731      0.023     11.801      0.000       0.228       0.318
C(country)[T.218]        -0.1196      0.024     -5.038      0.000      -0.166      -0.073
C(country)[T.222]         0.1499      0.018      8.267      0.000       0.114       0.185
C(country)[T.320]         0.3794      0.027     13.822      0.000       0.326       0.433
C(country)[T.340]         0.3014      0.024     12.383      0.000       0.254       0.349
C(country)[T.484]         0.1933      0.019     10.033      0.000       0.156       0.231
C(country)[T.558]         0.1785      0.034      5.287      0.000       0.112       0.245
C(country)[T.591]         0.2978      0.043      6.878      0.000       0.213       0.383
C(country)[T.600]         0.0712      0.023      3.087      0.002       0.026       0.116
C(country)[T.604]        -0.2747      0.022    -12.654      0.000      -0.317      -0.232
C(country)[T.858]        -0.0245      0.017     -1.434      0.152      -0.058       0.009
C(country)[T.862]         0.3089      0.023     13.653      0.000       0.265       0.353
interest_politics_z       0.0175      0.004      4.647      0.000       0.010       0.025
left_right_distance_z     0.0152      0.003      4.668      0.000       0.009       0.022
age_z                    -0.0292      0.004     -7.511      0.000      -0.037      -0.022
education_z               0.0824      0.005     17.126      0.000       0.073       0.092
econ_country_z            0.1647      0.003     48.386      0.000       0.158       0.171
sex                      -0.0028      0.005     -0.570      0.569      -0.012       0.007
trust_people              0.1006      0.012      8.657      0.000       0.078       0.123
==============================================================================
Omnibus:                     6313.243   Durbin-Watson:                   1.769
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5318.831
Skew:                          -0.338   Prob(JB):                         0.00
Kurtosis:                       2.546   Cond. No.                         22.8
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [41]:
################### MODELO 6 ################

#df_clean = df_reg.loc[df_reg["wave"] > 2019].copy()
df_clean = df_reg.copy()


df_clean["polar_country_wave_z"] = (
    df_clean
    .groupby(["country","wave"])["left_right_distance_z"]
    .transform("mean")
)

df_clean["polar_within_z"] = (
    df_clean["left_right_distance_z"] - df_clean["polar_country_wave_z"]
)


multinivel = smf.ols(
    """life_satisfaction_z ~ polar_within_z + polar_country_wave_z
             + interest_politics_z
             + interest_politics_z:polar_within_z
             + interest_politics_z:polar_country_wave_z

             + age_z + education_z +econ_country_z + sex + trust_people

             + C(country) + C(wave)""",
    data=df_clean
).fit(cov_type="cluster", cov_kwds={"groups": df_clean["country"]})

print(multinivel.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.085
Model:                             OLS   Adj. R-squared:                  0.085
Method:                  Least Squares   F-statistic:                     55.68
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):           1.38e-11
Time:                         14:41:15   Log-Likelihood:            -2.6533e+05
No. Observations:               192272   AIC:                         5.307e+05
Df Residuals:                   192232   BIC:                         5.311e+05
Df Model:                           39
Covariance Type:               cluster
============================================================================================================
                                               coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                   -0.0899      0.042     -2.127      0.033      -0.173      -0.007
C(country)[T.68]                            -0.2899      0.007    -40.160      0.000      -0.304      -0.276
C(country)[T.76]                            -0.1834      0.026     -7.153      0.000      -0.234      -0.133
C(country)[T.152]                           -0.1463      0.007    -21.070      0.000      -0.160      -0.133
C(country)[T.170]                            0.2861      0.019     14.890      0.000       0.248       0.324
C(country)[T.188]                            0.4408      0.026     16.731      0.000       0.389       0.492
C(country)[T.214]                            0.2134      0.052      4.086      0.000       0.111       0.316
C(country)[T.218]                           -0.1376      0.017     -8.061      0.000      -0.171      -0.104
C(country)[T.222]                            0.1152      0.029      3.925      0.000       0.058       0.173
C(country)[T.320]                            0.3501      0.026     13.424      0.000       0.299       0.401
C(country)[T.340]                            0.2425      0.048      5.067      0.000       0.149       0.336
C(country)[T.484]                            0.1708      0.019      8.961      0.000       0.133       0.208
C(country)[T.558]                            0.1180      0.049      2.393      0.017       0.021       0.215
C(country)[T.591]                            0.2651      0.029      9.242      0.000       0.209       0.321
C(country)[T.600]                            0.0593      0.013      4.676      0.000       0.034       0.084
C(country)[T.604]                           -0.2809      0.008    -35.642      0.000      -0.296      -0.265
C(country)[T.858]                           -0.0506      0.023     -2.207      0.027      -0.095      -0.006
C(country)[T.862]                            0.2657      0.038      6.932      0.000       0.191       0.341
C(wave)[T.2000]                              0.0151      0.058      0.260      0.795      -0.098       0.128
C(wave)[T.2001]                              0.0153      0.048      0.316      0.752      -0.080       0.110
C(wave)[T.2003]                              0.0301      0.051      0.585      0.558      -0.071       0.131
C(wave)[T.2004]                              0.0136      0.052      0.264      0.792      -0.087       0.115
C(wave)[T.2005]                              0.0172      0.044      0.387      0.698      -0.070       0.104
C(wave)[T.2007]                              0.0188      0.049      0.382      0.702      -0.077       0.115
C(wave)[T.2009]                             -0.0133      0.051     -0.263      0.793      -0.112       0.086
C(wave)[T.2010]                             -0.0013      0.056     -0.024      0.981      -0.111       0.109
C(wave)[T.2013]                              0.0183      0.055      0.335      0.737      -0.089       0.126
C(wave)[T.2020]                              0.0177      0.063      0.283      0.777      -0.105       0.140
C(wave)[T.2023]                              0.0278      0.069      0.403      0.687      -0.107       0.163
C(wave)[T.2024]                              0.0212      0.064      0.333      0.739      -0.104       0.146
polar_within_z                               0.0137      0.003      4.086      0.000       0.007       0.020
polar_country_wave_z                         0.1023      0.070      1.463      0.144      -0.035       0.239
interest_politics_z                          0.0189      0.005      4.168      0.000       0.010       0.028
interest_politics_z:polar_within_z          -0.0022      0.003     -0.750      0.453      -0.008       0.003
interest_politics_z:polar_country_wave_z    -0.0394      0.012     -3.181      0.001      -0.064      -0.015
age_z                                       -0.0289      0.009     -3.181      0.001      -0.047      -0.011
education_z                                  0.0822      0.009      8.833      0.000       0.064       0.100
econ_country_z                               0.1649      0.011     15.471      0.000       0.144       0.186
sex                                         -0.0032      0.009     -0.366      0.714      -0.020       0.014
trust_people                                 0.1011      0.009     10.689      0.000       0.083       0.120
==============================================================================
Omnibus:                     6312.692   Durbin-Watson:                   1.769
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5322.962
Skew:                          -0.339   Prob(JB):                         0.00
Kurtosis:                       2.547   Cond. No.                         27.5
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 39, but rank is 17
  warnings.warn('covariance of constraints does not have full '

# Robustez y otros

In [25]:
################### Ciudad ################
df_clean = df_reg.copy()


df_clean["polar_city_wave_z"] = (
    df_clean
    .groupby(["city","wave"])["left_right_distance_z"]
    .transform("mean")
)

df_clean["polar_within_z"] = (
    df_clean["left_right_distance_z"] - df_clean["polar_city_wave_z"]
)

multinivel = smf.ols(
    """life_satisfaction_z ~ polar_within_z + polar_city_wave_z
             + interest_politics_z
             + interest_politics_z:polar_within_z
             + interest_politics_z:polar_city_wave_z

             + age_z + education_z + econ_country_z + sex + trust_people
             + C(country) + C(wave)""",
    data=df_clean
).fit(cov_type="cluster", cov_kwds={"groups": df_clean["city"]})

print(multinivel.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.086
Model:                             OLS   Adj. R-squared:                  0.085
Method:                  Least Squares   F-statistic:                     236.8
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):               0.00
Time:                         14:23:35   Log-Likelihood:            -2.6532e+05
No. Observations:               192272   AIC:                         5.307e+05
Df Residuals:                   192232   BIC:                         5.311e+05
Df Model:                           39
Covariance Type:               cluster
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                -0.1026      0.027     -3.826      0.000      -0.155      -0.050
C(country)[T.68]                         -0.2876      0.026    -10.981      0.000      -0.339      -0.236
C(country)[T.76]                         -0.1685      0.019     -9.010      0.000      -0.205      -0.132
C(country)[T.152]                        -0.1438      0.030     -4.798      0.000      -0.203      -0.085
C(country)[T.170]                         0.2964      0.023     13.023      0.000       0.252       0.341
C(country)[T.188]                         0.4572      0.022     20.849      0.000       0.414       0.500
C(country)[T.214]                         0.2443      0.024     10.111      0.000       0.197       0.292
C(country)[T.218]                        -0.1279      0.024     -5.246      0.000      -0.176      -0.080
C(country)[T.222]                         0.1336      0.019      7.183      0.000       0.097       0.170
C(country)[T.320]                         0.3662      0.028     13.263      0.000       0.312       0.420
C(country)[T.340]                         0.2753      0.024     11.258      0.000       0.227       0.323
C(country)[T.484]                         0.1827      0.020      9.236      0.000       0.144       0.221
C(country)[T.558]                         0.1487      0.036      4.117      0.000       0.078       0.219
C(country)[T.591]                         0.2825      0.044      6.372      0.000       0.196       0.369
C(country)[T.600]                         0.0654      0.023      2.784      0.005       0.019       0.111
C(country)[T.604]                        -0.2775      0.021    -13.013      0.000      -0.319      -0.236
C(country)[T.858]                        -0.0374      0.017     -2.152      0.031      -0.071      -0.003
C(country)[T.862]                         0.2881      0.023     12.499      0.000       0.243       0.333
C(wave)[T.2000]                           0.0144      0.034      0.422      0.673      -0.052       0.081
C(wave)[T.2001]                           0.0168      0.025      0.668      0.504      -0.032       0.066
C(wave)[T.2003]                           0.0322      0.027      1.190      0.234      -0.021       0.085
C(wave)[T.2004]                           0.0135      0.024      0.555      0.579      -0.034       0.061
C(wave)[T.2005]                           0.0160      0.025      0.644      0.519      -0.033       0.065
C(wave)[T.2007]                           0.0178      0.028      0.646      0.518      -0.036       0.072
C(wave)[T.2009]                          -0.0141      0.028     -0.503      0.615      -0.069       0.041
C(wave)[T.2010]                          -0.0020      0.032     -0.064      0.949      -0.065       0.060
C(wave)[T.2013]                           0.0178      0.027      0.650      0.516      -0.036       0.071
C(wave)[T.2020]                           0.0159      0.029      0.541      0.588      -0.042       0.074
C(wave)[T.2023]                           0.0270      0.031      0.863      0.388      -0.034       0.088
C(wave)[T.2024]                           0.0208      0.031      0.671      0.502      -0.040       0.082
polar_within_z                            0.0086      0.003      3.066      0.002       0.003       0.014
polar_city_wave_z                         0.0580      0.011      5.182      0.000       0.036       0.080
interest_politics_z                       0.0185      0.004      4.912      0.000       0.011       0.026
interest_politics_z:polar_within_z       -0.0012      0.003     -0.488      0.626      -0.006       0.004
interest_politics_z:polar_city_wave_z    -0.0193      0.006     -3.151      0.002      -0.031      -0.007
age_z                                    -0.0285      0.004     -7.372      0.000      -0.036      -0.021
education_z                               0.0831      0.005     17.168      0.000       0.074       0.093
econ_country_z                            0.1648      0.003     48.699      0.000       0.158       0.171
sex                                      -0.0031      0.005     -0.651      0.515      -0.013       0.006
trust_people                              0.1012      0.012      8.705      0.000       0.078       0.124
==============================================================================
Omnibus:                     6309.780   Durbin-Watson:                   1.769
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5324.678
Skew:                          -0.339   Prob(JB):                         0.00
Kurtosis:                       2.547   Cond. No.                         23.4
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

# Colapsar a Nivel Ciudad

In [26]:
# =========================
# 1. colapsar city-wave
# =========================

df_city = (
    df_reg
    .groupby(["country", "city", "wave"])
    .agg({
        "life_satisfaction_z": "mean",
        "left_right_distance_z": "mean",
        "interest_politics_z": "mean",
        "age_z": "mean",
        "education_z": "mean",
        "econ_country_z": "mean",
        "sex": "mean",
        "trust_people": "mean"
    })
    .reset_index()
)

In [27]:
################ Modelo simple a nivel ciudad #############

model_city = smf.ols(
    """
    life_satisfaction_z ~
    left_right_distance_z +
    interest_politics_z +
    age_z +
    education_z +
    econ_country_z +
    sex +
    trust_people +
    C(country) +
    C(wave)
    """,
    data=df_city
).fit(
    cov_type="cluster",
    cov_kwds={"groups": df_city["country"]}
)

print(model_city.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.229
Model:                             OLS   Adj. R-squared:                  0.226
Method:                  Least Squares   F-statistic:                     1471.
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):           1.47e-23
Time:                         14:23:35   Log-Likelihood:                -6710.7
No. Observations:                11229   AIC:                         1.350e+04
Df Residuals:                    11192   BIC:                         1.377e+04
Df Model:                           36
Covariance Type:               cluster
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                -0.0236      0.064     -0.370      0.711      -0.148       0.101
C(country)[T.68]         -0.3215      0.029    -11.110      0.000      -0.378      -0.265
C(country)[T.76]         -0.2415      0.035     -6.996      0.000      -0.309      -0.174
C(country)[T.152]        -0.1999      0.022     -9.004      0.000      -0.243      -0.156
C(country)[T.170]         0.2830      0.035      8.004      0.000       0.214       0.352
C(country)[T.188]         0.4282      0.033     13.140      0.000       0.364       0.492
C(country)[T.214]         0.2227      0.029      7.712      0.000       0.166       0.279
C(country)[T.218]        -0.1541      0.031     -5.051      0.000      -0.214      -0.094
C(country)[T.222]         0.1009      0.035      2.877      0.004       0.032       0.170
C(country)[T.320]         0.3642      0.034     10.871      0.000       0.299       0.430
C(country)[T.340]         0.3090      0.033      9.449      0.000       0.245       0.373
C(country)[T.484]         0.1422      0.029      4.913      0.000       0.085       0.199
C(country)[T.558]         0.1539      0.039      3.982      0.000       0.078       0.230
C(country)[T.591]         0.1785      0.032      5.531      0.000       0.115       0.242
C(country)[T.600]         0.0255      0.021      1.192      0.233      -0.016       0.068
C(country)[T.604]        -0.3045      0.025    -12.144      0.000      -0.354      -0.255
C(country)[T.858]        -0.0556      0.032     -1.754      0.079      -0.118       0.007
C(country)[T.862]         0.2442      0.028      8.783      0.000       0.190       0.299
C(wave)[T.2000]          -0.1134      0.074     -1.542      0.123      -0.258       0.031
C(wave)[T.2001]          -0.0525      0.077     -0.679      0.497      -0.204       0.099
C(wave)[T.2003]          -0.0314      0.064     -0.488      0.626      -0.158       0.095
C(wave)[T.2004]          -0.0463      0.061     -0.757      0.449      -0.166       0.074
C(wave)[T.2005]          -0.0395      0.046     -0.853      0.394      -0.130       0.051
C(wave)[T.2007]          -0.0274      0.045     -0.606      0.544      -0.116       0.061
C(wave)[T.2009]          -0.0817      0.057     -1.442      0.149      -0.193       0.029
C(wave)[T.2010]          -0.0642      0.056     -1.155      0.248      -0.173       0.045
C(wave)[T.2013]          -0.0385      0.053     -0.720      0.472      -0.143       0.066
C(wave)[T.2020]          -0.0649      0.069     -0.941      0.346      -0.200       0.070
C(wave)[T.2023]          -0.0463      0.081     -0.568      0.570      -0.206       0.113
C(wave)[T.2024]          -0.0442      0.078     -0.570      0.569      -0.196       0.108
left_right_distance_z     0.0460      0.015      3.106      0.002       0.017       0.075
interest_politics_z       0.0072      0.012      0.595      0.552      -0.017       0.031
age_z                    -0.0154      0.031     -0.492      0.623      -0.077       0.046
education_z               0.0856      0.018      4.867      0.000       0.051       0.120
econ_country_z            0.2008      0.028      7.157      0.000       0.146       0.256
sex                       0.0392      0.048      0.817      0.414      -0.055       0.133
trust_people          -4.081e-05      0.047     -0.001      0.999      -0.091       0.091
==============================================================================
Omnibus:                      545.946   Durbin-Watson:                   1.881
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1218.793
Skew:                          -0.316   Prob(JB):                    2.20e-265
Kurtosis:                       4.485   Cond. No.                         38.9
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 36, but rank is 17
  warnings.warn('covariance of constraints does not have full '

In [28]:
########### Modelo con Lags a nivel Ciudad ####################


valid_cities = (
    df_city
    .groupby("city")["wave"]
    .nunique()
)

valid_cities = valid_cities[valid_cities >= 6].index

df_city_dyn = df_city[df_city["city"].isin(valid_cities)].copy()


# ordenar panel
df_city_dyn = df_city_dyn.sort_values(["city", "wave"]).copy()

# crear lags
df_city_dyn["polar_lag"] = (
    df_city_dyn
    .groupby("city")["left_right_distance_z"]
    .shift(1)
)

df_city_dyn["life_lag"] = (
    df_city_dyn
    .groupby("city")["life_satisfaction_z"]
    .shift(1)
)

df_city_dyn["interest_lag"] = (
    df_city_dyn
    .groupby("city")["interest_politics_z"]
    .shift(1)
)

# variables del modelo
vars_model = [
    "life_satisfaction_z",
    "polar_lag",
    "life_lag",
    "interest_lag",
    "left_right_distance_z",
    "interest_politics_z",
    "econ_country_z",
    "city",
    "wave",
    "trust_people",
    "sex"
]

# eliminar missings
df_model = df_city_dyn[vars_model].dropna().copy()

# modelo dinámico
model_dyn = smf.ols(
    """
    life_satisfaction_z ~
    polar_lag +
    life_lag +
    interest_lag +

    interest_politics_z +
    left_right_distance_z +

    econ_country_z +
    sex +
    trust_people +


    C(wave)
    """,
    data=df_model
).fit(
    cov_type="cluster",
    cov_kwds={"groups": df_model["city"]}
)

print(model_dyn.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.159
Model:                             OLS   Adj. R-squared:                  0.155
Method:                  Least Squares   F-statistic:                     31.13
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):           7.00e-74
Time:                         14:23:36   Log-Likelihood:                -2400.3
No. Observations:                 4078   AIC:                             4841.
Df Residuals:                     4058   BIC:                             4967.
Df Model:                           19
Covariance Type:               cluster
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                -0.1128      0.050     -2.259      0.024      -0.211      -0.015
C(wave)[T.2001]           0.1155      0.052      2.226      0.026       0.014       0.217
C(wave)[T.2003]           0.1593      0.047      3.386      0.001       0.067       0.251
C(wave)[T.2004]           0.0877      0.047      1.869      0.062      -0.004       0.180
C(wave)[T.2005]           0.1383      0.045      3.082      0.002       0.050       0.226
C(wave)[T.2007]           0.1405      0.046      3.029      0.002       0.050       0.231
C(wave)[T.2009]           0.0500      0.047      1.060      0.289      -0.042       0.142
C(wave)[T.2010]           0.0463      0.046      1.007      0.314      -0.044       0.136
C(wave)[T.2013]           0.1298      0.045      2.859      0.004       0.041       0.219
C(wave)[T.2020]           0.0760      0.048      1.589      0.112      -0.018       0.170
C(wave)[T.2023]           0.1066      0.044      2.410      0.016       0.020       0.193
C(wave)[T.2024]           0.0718      0.045      1.591      0.112      -0.017       0.160
polar_lag                 0.0530      0.016      3.211      0.001       0.021       0.085
life_lag                  0.2913      0.019     15.635      0.000       0.255       0.328
interest_lag             -0.0336      0.018     -1.826      0.068      -0.070       0.002
interest_politics_z       0.0083      0.020      0.406      0.685      -0.032       0.048
left_right_distance_z     0.0975      0.018      5.435      0.000       0.062       0.133
econ_country_z            0.1713      0.016     10.672      0.000       0.140       0.203
sex                       0.0047      0.062      0.076      0.939      -0.117       0.127
trust_people              0.1346      0.047      2.883      0.004       0.043       0.226
==============================================================================
Omnibus:                      100.505   Durbin-Watson:                   2.063
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              148.757
Skew:                          -0.258   Prob(JB):                     4.99e-33
Kurtosis:                       3.780   Cond. No.                         29.2
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [29]:
################# Modelo con Lags y change a nivel Ciudad ####################


# ordenar
df_city_dyn = df_city_dyn.sort_values(["city", "wave"]).copy()

# lags
df_city_dyn["life_lag"] = (
    df_city_dyn
    .groupby("city")["life_satisfaction_z"]
    .shift(1)
)

df_city_dyn["polar_lag"] = (
    df_city_dyn
    .groupby("city")["left_right_distance_z"]
    .shift(1)
)

df_city_dyn["interest_lag"] = (
    df_city_dyn
    .groupby("city")["interest_politics_z"]
    .shift(1)
)

# cambios
df_city_dyn["polar_change"] = (
    df_city_dyn
    .groupby("city")["left_right_distance_z"]
    .diff()
)

df_city_dyn["interest_change"] = (
    df_city_dyn
    .groupby("city")["interest_politics_z"]
    .diff()
)

# base limpia para el modelo
vars_model = [
    "life_satisfaction_z",
    "life_lag",
    "polar_lag",
    "interest_lag",
    "polar_change",
    "interest_change",
    "interest_politics_z",
    "left_right_distance_z",
    "econ_country_z",
    "sex",
    "trust_people",
    "wave",
    "city",
    "country"
]

df_model = (
    df_city_dyn[vars_model]
    .dropna()
    .copy()
)

# modelo
model_dyn2 = smf.ols(
    """
    life_satisfaction_z ~
    life_lag +


    polar_change +
    interest_change +

    interest_politics_z +
    left_right_distance_z +

    econ_country_z +
    sex+
    trust_people +
    C(wave)+
    C(country)
    """,
    data=df_model
).fit(
    cov_type="cluster",
    cov_kwds={"groups": df_model["city"]}
)

print(model_dyn2.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.306
Model:                             OLS   Adj. R-squared:                  0.300
Method:                  Least Squares   F-statistic:                     57.63
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):          3.13e-159
Time:                         14:23:36   Log-Likelihood:                -2010.0
No. Observations:                 4078   AIC:                             4094.
Df Residuals:                     4041   BIC:                             4328.
Df Model:                           36
Covariance Type:               cluster
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.0088      0.055      0.161      0.872      -0.098       0.116
C(wave)[T.2001]           0.0451      0.047      0.956      0.339      -0.047       0.138
C(wave)[T.2003]           0.0418      0.044      0.947      0.344      -0.045       0.128
C(wave)[T.2004]          -0.0172      0.044     -0.395      0.693      -0.103       0.068
C(wave)[T.2005]           0.0123      0.043      0.286      0.775      -0.072       0.096
C(wave)[T.2007]           0.0215      0.044      0.484      0.628      -0.065       0.108
C(wave)[T.2009]          -0.0390      0.045     -0.866      0.387      -0.127       0.049
C(wave)[T.2010]          -0.0470      0.045     -1.054      0.292      -0.134       0.040
C(wave)[T.2013]           0.0106      0.044      0.241      0.810      -0.076       0.097
C(wave)[T.2020]          -0.0109      0.046     -0.236      0.813      -0.101       0.080
C(wave)[T.2023]           0.0078      0.044      0.177      0.860      -0.078       0.094
C(wave)[T.2024]          -0.0213      0.044     -0.485      0.628      -0.108       0.065
C(country)[T.68]         -0.3395      0.055     -6.187      0.000      -0.447      -0.232
C(country)[T.76]         -0.3020      0.038     -7.966      0.000      -0.376      -0.228
C(country)[T.152]        -0.2303      0.038     -6.057      0.000      -0.305      -0.156
C(country)[T.170]         0.2470      0.061      4.069      0.000       0.128       0.366
C(country)[T.188]         0.3351      0.033     10.028      0.000       0.270       0.401
C(country)[T.214]         0.0818      0.048      1.710      0.087      -0.012       0.176
C(country)[T.218]        -0.1441      0.040     -3.632      0.000      -0.222      -0.066
C(country)[T.222]         0.0361      0.035      1.042      0.297      -0.032       0.104
C(country)[T.320]         0.2915      0.040      7.359      0.000       0.214       0.369
C(country)[T.340]         0.1279      0.041      3.134      0.002       0.048       0.208
C(country)[T.484]         0.1151      0.034      3.345      0.001       0.048       0.182
C(country)[T.558]         0.0527      0.044      1.201      0.230      -0.033       0.139
C(country)[T.591]         0.1919      0.039      4.941      0.000       0.116       0.268
C(country)[T.600]         0.0715      0.031      2.313      0.021       0.011       0.132
C(country)[T.604]        -0.2803      0.041     -6.913      0.000      -0.360      -0.201
C(country)[T.858]        -0.1193      0.040     -2.951      0.003      -0.198      -0.040
C(country)[T.862]         0.1644      0.041      3.994      0.000       0.084       0.245
life_lag                  0.0953      0.018      5.240      0.000       0.060       0.131
polar_change              0.0007      0.016      0.043      0.966      -0.030       0.031
interest_change           0.0147      0.017      0.867      0.386      -0.019       0.048
interest_politics_z       0.0028      0.024      0.118      0.906      -0.044       0.050
left_right_distance_z     0.0400      0.023      1.771      0.077      -0.004       0.084
econ_country_z            0.2137      0.017     12.685      0.000       0.181       0.247
sex                      -0.0037      0.060     -0.063      0.950      -0.121       0.113
trust_people              0.0286      0.045      0.637      0.524      -0.060       0.117
==============================================================================
Omnibus:                      155.381   Durbin-Watson:                   2.039
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              304.337
Skew:                          -0.277   Prob(JB):                     8.21e-67
Kurtosis:                       4.219   Cond. No.                         39.4
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

# Colapsar a nivel País

In [30]:
# =========================
# 1. colapsar country-wave
# =========================

df_country = (
    df_reg
    .groupby(["country", "wave"])
    .agg({
        "life_satisfaction_z": "mean",
        "left_right_distance_z": "mean",
        "interest_politics_z": "mean",
        "age_z": "mean",
        "education_z": "mean",
        "econ_country_z": "mean",
        "sex": "mean",
        "trust_people": "mean"
    })
    .reset_index()
)

In [31]:
############## Modelo simple a nivel país #########################


model_country = smf.ols(
    """
    life_satisfaction_z ~
    left_right_distance_z +
    interest_politics_z +
    age_z +
    education_z +
    econ_country_z +
    sex +
    trust_people +
    C(country) +
    C(wave)
    """,
    data=df_country
).fit(
    cov_type="cluster",
    cov_kwds={"groups": df_country["country"]}
)

print(model_country.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.735
Model:                             OLS   Adj. R-squared:                  0.685
Method:                  Least Squares   F-statistic:                     5.464
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):           0.000532
Time:                         14:23:36   Log-Likelihood:                 126.97
No. Observations:                  228   AIC:                            -179.9
Df Residuals:                      191   BIC:                            -53.06
Df Model:                           36
Covariance Type:               cluster
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.4962      0.374      1.326      0.185      -0.237       1.230
C(country)[T.68]         -0.3676      0.066     -5.559      0.000      -0.497      -0.238
C(country)[T.76]         -0.2820      0.062     -4.521      0.000      -0.404      -0.160
C(country)[T.152]        -0.2162      0.045     -4.837      0.000      -0.304      -0.129
C(country)[T.170]         0.2150      0.049      4.357      0.000       0.118       0.312
C(country)[T.188]         0.3642      0.047      7.679      0.000       0.271       0.457
C(country)[T.214]         0.1854      0.068      2.715      0.007       0.052       0.319
C(country)[T.218]        -0.2222      0.056     -3.980      0.000      -0.332      -0.113
C(country)[T.222]         0.0020      0.068      0.029      0.977      -0.131       0.135
C(country)[T.320]         0.2222      0.079      2.800      0.005       0.067       0.378
C(country)[T.340]         0.1488      0.078      1.916      0.055      -0.003       0.301
C(country)[T.484]         0.1100      0.060      1.845      0.065      -0.007       0.227
C(country)[T.558]         0.0318      0.090      0.354      0.724      -0.145       0.208
C(country)[T.591]         0.2087      0.051      4.076      0.000       0.108       0.309
C(country)[T.600]         0.0369      0.040      0.930      0.353      -0.041       0.115
C(country)[T.604]        -0.3340      0.054     -6.140      0.000      -0.441      -0.227
C(country)[T.858]        -0.0979      0.068     -1.444      0.149      -0.231       0.035
C(country)[T.862]         0.1984      0.065      3.037      0.002       0.070       0.326
C(wave)[T.2000]          -0.0068      0.066     -0.103      0.918      -0.137       0.123
C(wave)[T.2001]           0.0162      0.063      0.257      0.798      -0.107       0.140
C(wave)[T.2003]           0.0527      0.067      0.787      0.431      -0.078       0.184
C(wave)[T.2004]           0.0214      0.065      0.331      0.741      -0.106       0.148
C(wave)[T.2005]           0.0206      0.054      0.381      0.703      -0.085       0.127
C(wave)[T.2007]           0.0072      0.056      0.127      0.899      -0.103       0.118
C(wave)[T.2009]          -0.0303      0.055     -0.551      0.582      -0.138       0.077
C(wave)[T.2010]          -0.0189      0.059     -0.320      0.749      -0.135       0.097
C(wave)[T.2013]          -0.0139      0.054     -0.258      0.796      -0.120       0.092
C(wave)[T.2020]          -0.0074      0.065     -0.115      0.908      -0.134       0.119
C(wave)[T.2023]          -0.0095      0.069     -0.138      0.890      -0.145       0.126
C(wave)[T.2024]          -0.0069      0.066     -0.105      0.916      -0.136       0.123
left_right_distance_z     0.0595      0.084      0.709      0.478      -0.105       0.224
interest_politics_z      -0.0493      0.089     -0.551      0.582      -0.225       0.126
age_z                    -0.1596      0.198     -0.806      0.420      -0.548       0.228
education_z               0.0027      0.075      0.036      0.971      -0.143       0.149
econ_country_z            0.2681      0.062      4.306      0.000       0.146       0.390
sex                      -0.9309      0.715     -1.302      0.193      -2.332       0.470
trust_people             -0.0789      0.231     -0.341      0.733      -0.533       0.375
==============================================================================
Omnibus:                        8.947   Durbin-Watson:                   1.603
Prob(Omnibus):                  0.011   Jarque-Bera (JB):               17.386
Skew:                           0.021   Prob(JB):                     0.000168
Kurtosis:                       4.352   Cond. No.                         79.6
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 36, but rank is 17
  warnings.warn('covariance of constraints does not have full '

In [32]:
########### Modelo con Lags - Nivel País ####################

# quedarnos con países con suficientes waves
valid_countries = (
    df_country
    .groupby("country")["wave"]
    .nunique()
)

valid_countries = valid_countries[valid_countries >= 6].index

df_country_dyn = (
    df_country[df_country["country"].isin(valid_countries)]
    .copy()
)

# ordenar panel
df_country_dyn = (
    df_country_dyn
    .sort_values(["country", "wave"])
    .copy()
)

# crear lags
df_country_dyn["polar_lag"] = (
    df_country_dyn
    .groupby("country")["left_right_distance_z"]
    .shift(1)
)

df_country_dyn["life_lag"] = (
    df_country_dyn
    .groupby("country")["life_satisfaction_z"]
    .shift(1)
)

df_country_dyn["interest_lag"] = (
    df_country_dyn
    .groupby("country")["interest_politics_z"]
    .shift(1)
)

# variables del modelo
vars_model = [
    "life_satisfaction_z",
    "polar_lag",
    "life_lag",
    "interest_lag",
    "interest_politics_z",
    "econ_country_z",
    "country",
    "wave",
    "trust_people",
    "sex"
]

# eliminar missings
df_model = (
    df_country_dyn[vars_model]
    .dropna()
    .copy()
)

# modelo dinámico
model_dyn_country = smf.ols(
    """
    life_satisfaction_z ~
    polar_lag +
    life_lag +
    interest_lag +
    econ_country_z +
    sex +
    trust_people +
    C(wave)
    """,
    data=df_model
).fit(
    cov_type="cluster",
    cov_kwds={"groups": df_model["country"]}
)

print(model_dyn_country.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.644
Model:                             OLS   Adj. R-squared:                  0.613
Method:                  Least Squares   F-statistic:                     988.7
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):           4.29e-22
Time:                         14:23:36   Log-Likelihood:                 85.195
No. Observations:                  210   AIC:                            -134.4
Df Residuals:                      192   BIC:                            -74.14
Df Model:                           17
Covariance Type:               cluster
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           0.1403      0.300      0.467      0.640      -0.448       0.729
C(wave)[T.2001]    -0.0017      0.104     -0.016      0.987      -0.205       0.202
C(wave)[T.2003]     0.0359      0.079      0.453      0.650      -0.119       0.191
C(wave)[T.2004]    -0.0165      0.041     -0.398      0.691      -0.098       0.065
C(wave)[T.2005]     0.0068      0.066      0.104      0.918      -0.122       0.136
C(wave)[T.2007]     0.0012      0.053      0.023      0.982      -0.102       0.105
C(wave)[T.2009]    -0.0424      0.067     -0.629      0.529      -0.174       0.090
C(wave)[T.2010]    -0.0028      0.061     -0.046      0.963      -0.123       0.117
C(wave)[T.2013]    -0.0007      0.080     -0.009      0.993      -0.158       0.156
C(wave)[T.2020]    -0.0240      0.064     -0.374      0.708      -0.149       0.102
C(wave)[T.2023]     0.0084      0.061      0.137      0.891      -0.112       0.129
C(wave)[T.2024]    -0.0116      0.057     -0.204      0.839      -0.123       0.100
polar_lag           0.1226      0.041      3.003      0.003       0.043       0.203
life_lag            0.6907      0.054     12.677      0.000       0.584       0.797
interest_lag       -0.1837      0.099     -1.847      0.065      -0.379       0.011
econ_country_z      0.1170      0.045      2.615      0.009       0.029       0.205
sex                -0.2992      0.590     -0.507      0.612      -1.456       0.858
trust_people        0.2102      0.243      0.865      0.387      -0.266       0.686
==============================================================================
Omnibus:                       10.168   Durbin-Watson:                   2.366
Prob(Omnibus):                  0.006   Jarque-Bera (JB):               18.179
Skew:                          -0.205   Prob(JB):                     0.000113
Kurtosis:                       4.382   Cond. No.                         60.6
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [33]:
################# Modelo con Lags y Change - Nivel País ####################

# ordenar
df_country_dyn = df_country_dyn.sort_values(["country", "wave"]).copy()

# lags
df_country_dyn["life_lag"] = (
    df_country_dyn
    .groupby("country")["life_satisfaction_z"]
    .shift(1)
)

df_country_dyn["polar_lag"] = (
    df_country_dyn
    .groupby("country")["left_right_distance_z"]
    .shift(1)
)

df_country_dyn["interest_lag"] = (
    df_country_dyn
    .groupby("country")["interest_politics_z"]
    .shift(1)
)

# cambios
df_country_dyn["polar_change"] = (
    df_country_dyn
    .groupby("country")["left_right_distance_z"]
    .diff()
)

df_country_dyn["interest_change"] = (
    df_country_dyn
    .groupby("country")["interest_politics_z"]
    .diff()
)

# base limpia para el modelo
vars_model = [
    "life_satisfaction_z",
    "life_lag",

    "polar_change",
    "interest_change",
    "econ_country_z",
    "sex",
    "trust_people",
    "wave",
    "country"
]

df_model = (
    df_country_dyn[vars_model]
    .dropna()
    .copy()
)

# modelo
model_dyn2_country = smf.ols(
    """
    life_satisfaction_z ~
    life_lag +

    polar_change +
    interest_change +
    econ_country_z +
    sex +
    trust_people +
    C(wave)
    """,
    data=df_model
).fit(
    cov_type="cluster",
    cov_kwds={"groups": df_model["country"]}
)

print(model_dyn2_country.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     life_satisfaction_z   R-squared:                       0.621
Model:                             OLS   Adj. R-squared:                  0.588
Method:                  Least Squares   F-statistic:                     144.6
Date:                 Tue, 23 Jun 2026   Prob (F-statistic):           4.90e-15
Time:                         14:23:36   Log-Likelihood:                 78.584
No. Observations:                  210   AIC:                            -121.2
Df Residuals:                      192   BIC:                            -60.92
Df Model:                           17
Covariance Type:               cluster
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          -0.0150      0.295     -0.051      0.959      -0.594       0.564
C(wave)[T.2001]    -0.0050      0.107     -0.046      0.963      -0.215       0.206
C(wave)[T.2003]     0.0344      0.077      0.448      0.654      -0.116       0.185
C(wave)[T.2004]    -0.0227      0.040     -0.564      0.573      -0.102       0.056
C(wave)[T.2005]     0.0104      0.067      0.155      0.877      -0.121       0.142
C(wave)[T.2007]    -0.0022      0.058     -0.038      0.970      -0.116       0.111
C(wave)[T.2009]    -0.0366      0.070     -0.525      0.600      -0.173       0.100
C(wave)[T.2010]     0.0048      0.066      0.073      0.942      -0.125       0.134
C(wave)[T.2013]     0.0061      0.086      0.071      0.943      -0.162       0.174
C(wave)[T.2020]    -0.0276      0.069     -0.401      0.689      -0.163       0.108
C(wave)[T.2023]     0.0111      0.061      0.182      0.856      -0.108       0.130
C(wave)[T.2024]    -0.0080      0.055     -0.144      0.885      -0.116       0.100
life_lag            0.7502      0.056     13.321      0.000       0.640       0.861
polar_change       -0.0162      0.069     -0.233      0.815      -0.152       0.120
interest_change     0.0805      0.101      0.799      0.424      -0.117       0.278
econ_country_z      0.0868      0.042      2.086      0.037       0.005       0.168
sex                 0.0253      0.560      0.045      0.964      -1.072       1.123
trust_people        0.0694      0.250      0.277      0.782      -0.421       0.560
==============================================================================
Omnibus:                        9.995   Durbin-Watson:                   2.427
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               20.160
Skew:                          -0.112   Prob(JB):                     4.19e-05
Kurtosis:                       4.501   Cond. No.                         57.7
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)